const brain  = require('brain.js')

const greetings = async (req,res)=>{

}
 const trainingData = [
  {input:'Hello' , output:'greeting'},
  {input:'Hi' , output:'greeting'},
  {input:'Hey' , output:'greeting'},
  {input:'Good morning' , output:'greeting'},
  {input:'Good afternoon' , output:'greeting'},
  {input:'Good evening' , output:'greeting'},
  {input:'Good night' , output:'greeting'},
  {input:'Aloha' , output:'greeting'},
  {input:'Howdy' , output:'greeting'},
  {input:'Hi there' , output:'greeting'},
  {input:'Greetings' , output:'greeting'},
  {input:'What\s up' , output:'greeting'},
  {input:'Wagwan' , output:'greeting'},
  {input:'What\s going on' , output:'non-greeting'},
  {input:'Yo' , output:'greeting'},
  {input:'Yello' , output:'greeting'},
  {input:'Bonjour' , output:'greeting'},
  {input:'Hola' , output:'greeting'},
  {input:'Hiya' , output:'greeting'},
  {input:'Namaste' , output:'greeting'},
  {input:'How are you' , output:'non-greeting'},
  {input:'Goodbye' , output:'non-greeting'},
  {input:'Well done' , output:'non-greeting'},
  {input:'Please wait' , output:'non-greeting'},
  {input:'i don\t understand' , output:'non-greeting'},
  {input:'Yes' , output:'non-greeting'},
  {input:'No' , output:'non-greeting'},
  {input:'I\m sorry' , output:'non-greeting'},
  {input:'Thank you' , output:'non-greeting'},
  {input:'Howdy-do' , output:'non-greeting'},
  {input:'Wait' , output:'non-greeting'},
  {input:'Go' , output:'non-greeting'},
  {input:'Congratulations' , output:'non-greeting'},
  {input:'I understand' , output:'non-greeting'},
  {input:'Please' , output:'non-greeting'},
  {input:'I know' , output:'non-greeting'},
  {input:'No, ma\am' , output:'non-greeting'},
  {input:'Yes sir' , output:'non-greeting'},
  {input:'You\re welcome' , output:'non-greeting'},
  {input:'Sorry' , output:'non-greeting'},
  {input:'Maybe' , output:'non-greeting'},
  {input:'Help' , output:'non-greeting'},
  {input:'Me' , output:'non-greeting'},
  {input:'You' , output:'non-greeting'},
  {input:'You' , output:'greeting'},
  {input:'Congratulations' , output:'non-greeting'},
  {input:'How you dey', output:'greeting'},
  {input:'How your side', output:'greeting'},
  {input:'How are you?', output:'non-greeting'},
  {input:'How was your day', output:'non-greeting'},
  {input:'Wagwan', output:'greeting'},
  {input:'What\s up with you', output:'greeting'},
  {input:'What\s going on', output:'greeting'},
  {input:'What\s going on', output:'non-greeting'},
  {input:'Bonjour', output:'greeting'},
  {input:'Salut', output:'greeting'},
  {input:'Bonne nuit', output:'greeting'},
  {input:'Welcome', output:'greeting'},
  {input:'Salutations', output:'greeting'},
  {input:'Comment ça va', output:'greeting'},
  {input:'Enchanté(e)', output:'non-greeting'},
  {input:'Bonsoir', output:'greeting'},
  {input:'Coucou', output:'greeting'},
  {input:'inakwana', ouput:'greeting'}
 ]
